### PR TITLE
Legacy

### PR DESCRIPTION
**Pull request by satyanandatripathi**
Syntax error in 
play.py line 237 ( add bracket in ending of line 236🥺)

And line 517 as well

### CODE REVIEW

**Comment by InukaAsith** [comment]
Extreamply Sorry. 
Missed some parts

Sorry for that. I'm fixinng

**Comment by InukaAsith** [comment]
working now

**Comment by satyanandatripathi** [comment]
Pro

**Comment by InukaAsith** [comment]
> 
> 
> Syntax error in
> play.py line 237 ( add bracket in ending of line 236🥺)
> 
> And line 517 as well

@satyanandatripathi 
Many thanks for this detailed error message. 
That helped a lot in fixing.

**Comment by satyanandatripathi** [comment]
😘😘

**Pull request closed without merging**
